In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.model_selection import train_test_split

In [12]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the data
data = pd.read_csv('day.csv',parse_dates=True) 

# Preprocess the data

In [13]:
data=data.drop(['instant'],axis=1)
data.head()

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [14]:
# Normalize the features
scaler = StandardScaler()
scaler.fit(data['cnt'].values.reshape(-1,1))
data['cnt'] = scaler.transform(data['cnt'].values.reshape(-1, 1))

In [15]:
data.iloc[:,:-1]

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered
0,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654
1,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670
2,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229
3,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454
4,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,2012-12-27,1,1,12,0,4,1,2,0.254167,0.226642,0.652917,0.350133,247,1867
727,2012-12-28,1,1,12,0,5,1,2,0.253333,0.255046,0.590000,0.155471,644,2451
728,2012-12-29,1,1,12,0,6,0,2,0.253333,0.242400,0.752917,0.124383,159,1182
729,2012-12-30,1,1,12,0,0,0,1,0.255833,0.231700,0.483333,0.350754,364,1432
730,2012-12-31,1,1,12,0,1,1,2,0.215833,0.223487,0.577500,0.154846,439,2290

In [17]:
# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:,:-1], data.iloc[:,-1], test_size=0.1, random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(657, 14) (74, 14) (657,) (74,)

In [113]:
#Reshaping the data to adjust to the tensor
# Split the data into train and test sets

X_train_reshape = X_train.reshape((X_train.shape[0], 1, X_train.shape[1]))
X_test_reshape = X_test.reshape((X_test.shape[0], 1, X_test.shape[1]))
#Reshaping the data to adjust to the tensor
# Split the data into train and test sets

y_train_reshape = y_train.reshape((y_train.shape[0], 1, y_train.shape[1]))
y_test_reshape = y_test.reshape((y_test.shape[0], 1, y_test.shape[1]))

IndexError: tuple index out of range

In [93]:
X_train_reshape.shape

(657, 1, 11)

In [94]:
rnn = Sequential()

rnn.add(LSTM(128, input_shape=(X_train_reshape.shape[1], X_train_reshape.shape[2]))) # Pass 2nd and 3rd dimensions from the input matrix
rnn.add(Dense(units=1))

In [95]:
rnn.summary()

Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 lstm_11 (LSTM)              (None, 128)               71680

 dense_11 (Dense)            (None, 1)                 129

=================================================================
Total params: 71,809
Trainable params: 71,809
Non-trainable params: 0
_________________________________________________________________

In [96]:
rnn.compile(optimizer='SGD', loss='mse')
results = rnn.fit(X_train_reshape, y_train, validation_data=(X_test_reshape, y_test), epochs=20)

Epoch 1/20
21/21 [==============================] - 2s 25ms/step - loss: 0.2203 - val_loss: 0.1697
Epoch 2/20
21/21 [==============================] - 0s 5ms/step - loss: 0.1550 - val_loss: 0.1404
Epoch 3/20
21/21 [==============================] - 0s 5ms/step - loss: 0.1378 - val_loss: 0.1327
Epoch 4/20
21/21 [==============================] - 0s 5ms/step - loss: 0.1333 - val_loss: 0.1307
Epoch 5/20
21/21 [==============================] - 0s 4ms/step - loss: 0.1320 - val_loss: 0.1302
Epoch 6/20
21/21 [==============================] - 0s 5ms/step - loss: 0.1316 - val_loss: 0.1300
Epoch 7/20
21/21 [==============================] - 0s 5ms/step - loss: 0.1317 - val_loss: 0.1300
Epoch 8/20
21/21 [==============================] - 0s 5ms/step - loss: 0.1315 - val_loss: 0.1299
Epoch 9/20
21/21 [==============================] - 0s 5ms/step - loss: 0.1314 - val_loss: 0.1299
Epoch 10/20
21/21 [==============================] - 0s 4ms/step - loss: 0.1315 - val_loss: 0.1299
Epoch 11/20
21/21 [==============================] - 0s 5ms/step - loss: 0.1313 - val_loss: 0.1298
Epoch 12/20
21/21 [==============================] - 0s 4ms/step - loss: 0.1314 - val_loss: 0.1298
Epoch 13/20
21/21 [==============================] - 0s 4ms/step - loss: 0.1312 - val_loss: 0.1298
Epoch 14/20
21/21 [==============================] - 0s 4ms/step - loss: 0.1312 - val_loss: 0.1297
Epoch 15/20
21/21 [==============================] - 0s 5ms/step - loss: 0.1314 - val_loss: 0.1297
Epoch 16/20
21/21 [==============================] - 0s 4ms/step - loss: 0.1312 - val_loss: 0.1297
Epoch 17/20
21/21 [==============================] - 0s 5ms/step - loss: 0.1313 - val_loss: 0.1296
Epoch 18/20
21/21 [==============================] - 0s 5ms/step - loss: 0.1312 - val_loss: 0.1296
Epoch 19/20
21/21 [==============================] - 0s 4ms/step - loss: 0.1312 - val_loss: 0.1296
Epoch 20/20
21/21 [==============================] - 0s 4ms/step - loss: 0.1312 - val_loss: 0.1295

In [103]:
X_train.shape
# y_train.shape

(657, 11)

In [98]:
rnn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
rnn.fit(X_train, y_train, epochs=10, batch_size=32)

# Evaluate the model
loss, accuracy = rnn.evaluate(X_test, y_test)
print('Test Loss:', loss)
print('Test Accuracy:', accuracy)

# Make predictions
predictions = rnn.predict(X_test)

Epoch 1/10

ValueError: in user code:

    File "C:\Users\NHI623\AppData\Local\anaconda3\lib\site-packages\keras\engine\training.py", line 1160, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\NHI623\AppData\Local\anaconda3\lib\site-packages\keras\engine\training.py", line 1146, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\NHI623\AppData\Local\anaconda3\lib\site-packages\keras\engine\training.py", line 1135, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\NHI623\AppData\Local\anaconda3\lib\site-packages\keras\engine\training.py", line 993, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\NHI623\AppData\Local\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\NHI623\AppData\Local\anaconda3\lib\site-packages\keras\engine\input_spec.py", line 295, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential_12" is incompatible with the layer: expected shape=(None, 1, 11), found shape=(None, 11)